# Generated by Django 2.0 on 2017-12-28 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('points', models.FloatField()),
                ('city_state', models.CharField(max_length=255)),
                ('result_time', models.CharField(blank=True, max_length=255, null=True)),
                ('usac', models.IntegerField()),
                ('bib', models.IntegerField()),
                ('team', models.CharField(max_length=255)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usac.Participant')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usac.Race')),
            ],
        ),
    ]
