# Generated by Django 2.0 on 2017-12-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usac', '0002_raceresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='bib',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='city_state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='team',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='usac',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
